language: python
branches:
  only:
  - master
  
python:
  - "3.6"
   
install:
- pip3 install pelican 
- pip3 install git
- pip3 install nodejs 
- pip3 install npm 
- pip3 install markdown
- npm install --global surge

script:
- pelican content/ -s pelicanconf.py -t content/chunk/
deploy:
  provider: surge
  project: ./output/
  domain: adriansilva.surge.sh
skip_cleanup: true
